<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Penghuni;
use Illuminate\Support\Str;

class MigrasiPenghuni13Juli extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $penghuniLama = collect([
                [
                    'id' => "6f00293b-75a5-4fc5-a121-7dccf72afcdb",
                    'nama' => 'Abdufattah Yurianta',
                    'tempat_lahir' => 'Surabaya',
                    'tgl_lahir' => '2000-09-05',
                    'agama' => 'Islam',
                    'no_telp' => '+62 856-5510-3170',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Abdufattah Yurianta-2000-09-05.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Sama',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => "b5a702b4-b081-4ffd-b44e-5ea19f289b89",
                    'nama' => 'Sainah',
                    'tempat_lahir' => 'Pemalang',
                    'tgl_lahir' => '1981-10-17',
                    'agama' => 'Islam',
                    'no_telp' => null,
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Sainah -1981-10-17.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Sama',
                ],
                [
                    'id' => "2770cff3-f0f0-460e-9664-109481e37dd9",
                    'nama' => 'Muhammad Rizki Zamzami',
                    'tempat_lahir' => 'Sungai Belida',
                    'tgl_lahir' => '2002-05-26',
                    'agama' => 'Islam',
                    'no_telp' => null,
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Muhammad Rizki Zamzami -2002-05-26.jpeg',
                    'referensi' => null,
                    'status' => 'Out',
                    'status_nama' => 'Nama Sama',
                    'status_telp' => 'Telp Sama',
                ],
                [
                    'id' => "1ed6b0e9-8d9e-44d8-b66e-2a84bcd90554",
                    'nama' => 'Dino Rafly  Priatna',
                    'tempat_lahir' => 'Samarinda',
                    'tgl_lahir' => '2000-11-12',
                    'agama' => 'Islam',
                    'no_telp' => null,
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Dino Rafly  Priatna-2000-11-12.jpeg',
                    'referensi' => null,
                    'status' => 'Out',
                    'status_nama' => 'Nama Sama',
                    'status_telp' => 'Telp Sama',
                ],
                [
                    'id' => "503b984c-146d-4ce0-8dff-ff7698446db5",
                    'nama' => 'Leni Fatmawati',
                    'tempat_lahir' => 'Pemalang',
                    'tgl_lahir' => '1999-09-04',
                    'agama' => 'Islam',
                    'no_telp' => '+62 812-9529-1998',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Leni Fatmawati-1999-09-04.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Sama',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => "108e4412-b5c5-45ce-a5d0-a65d095a1217",
                    'nama' => 'Mutiah Kharisma Alenta',
                    'tempat_lahir' => 'Padang',
                    'tgl_lahir' => '1997-05-13',
                    'agama' => 'Islam',
                    'no_telp' => '+62 821-1131-8601',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Mutiah Kharisma Alenta -1997-05-13.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Sama',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1947,
                    'nama' => 'Elizabeth Deandra',
                    'tempat_lahir' => 'Karawang',
                    'tgl_lahir' => '2002-06-05',
                    'agama' => 'katholik',
                    'no_telp' => '+62 813-1076-0034',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Elizabeth Deandra -2002-06-05.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1948,
                    'nama' => 'Ali Supyan',
                    'tempat_lahir' => 'Tanjung Aji',
                    'tgl_lahir' => '1998-04-21',
                    'agama' => 'Islam',
                    'no_telp' => null,
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Ali Supyan -1998-04-21.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Sama',
                ],
                [
                    'id' => 1949,
                    'nama' => 'Marchelo Liandrey',
                    'tempat_lahir' => 'Bintuhan',
                    'tgl_lahir' => '2003-03-11',
                    'agama' => 'Islam',
                    'no_telp' => '+62 816-1730-2592',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Marchelo Liandrey -2003-03-11.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1950,
                    'nama' => 'Ekahadi Luthfi Tedja',
                    'tempat_lahir' => 'Jakarta',
                    'tgl_lahir' => '2006-03-25',
                    'agama' => 'Islam',
                    'no_telp' => '+62 822-5011-8070',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Ekahadi Luthfi Tedja -2006-03-25.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1951,
                    'nama' => 'Cut Nadila Abni',
                    'tempat_lahir' => 'Lhokseumawe',
                    'tgl_lahir' => '2001-02-12',
                    'agama' => 'Islam',
                    'no_telp' => '+62 821-2518-7881',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Cut Nadila Abni -2001-02-12.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1952,
                    'nama' => 'Nanda Namira Putri',
                    'tempat_lahir' => 'Bandung',
                    'tgl_lahir' => '2000-05-30',
                    'agama' => 'Islam',
                    'no_telp' => '+62 882-1973-1519',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Nanda Namira Putri -2000-05-30.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1953,
                    'nama' => 'Chika Diah Maulidiana',
                    'tempat_lahir' => 'Tangerang',
                    'tgl_lahir' => '2006-04-10',
                    'agama' => 'Islam',
                    'no_telp' => null,
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Chika Diah Maulidiana-2006-04-10.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Sama',
                ],
                [
                    'id' => 1954,
                    'nama' => 'Benedictus Reynold Richie',
                    'tempat_lahir' => 'Jember',
                    'tgl_lahir' => '2006-03-11',
                    'agama' => 'katholik',
                    'no_telp' => '+62 821-4176-6990',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Benedictus Reynold Richie -2006-03-11.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1955,
                    'nama' => 'Zahra Ainurrizka',
                    'tempat_lahir' => 'Tangerang',
                    'tgl_lahir' => '1997-10-02',
                    'agama' => 'Islam',
                    'no_telp' => '+62 813-1041-8004',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Zahra Ainurrizka-1997-10-02.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1956,
                    'nama' => 'Nathanael Haryadi',
                    'tempat_lahir' => 'Bandar Lampung',
                    'tgl_lahir' => '2003-09-20',
                    'agama' => 'Kristen',
                    'no_telp' => '+62 818-0528-5503',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Nathanael Haryadi -2003-09-20.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1957,
                    'nama' => 'Florence Nikita Lee',
                    'tempat_lahir' => 'Bandung',
                    'tgl_lahir' => '2003-05-12',
                    'agama' => 'katholik',
                    'no_telp' => '+62 851-5712-6221',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Florence Nikita Lee-2003-05-12.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1958,
                    'nama' => 'Leon Francesco Goenawan',
                    'tempat_lahir' => 'Bandung',
                    'tgl_lahir' => '2007-02-13',
                    'agama' => 'katholik',
                    'no_telp' => '+62 898-8805-189',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Leon Francesco Goenawan-2007-02-13.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1959,
                    'nama' => 'Rosalinda Oktaviani Assan',
                    'tempat_lahir' => 'Maumere',
                    'tgl_lahir' => '2003-10-08',
                    'agama' => 'Katholik',
                    'no_telp' => '+62 813-3952-5962',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Rosalinda Oktaviani Assan -2003-10-08.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1960,
                    'nama' => 'Quinnasya Alovenda',
                    'tempat_lahir' => 'Bandung',
                    'tgl_lahir' => '2002-09-21',
                    'agama' => 'Islam',
                    'no_telp' => '+62 822-1859-9838',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Quinnasya Alovenda -2002-09-21.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1961,
                    'nama' => 'Rohidin',
                    'tempat_lahir' => 'Wonosobo',
                    'tgl_lahir' => '1993-01-13',
                    'agama' => 'Islam',
                    'no_telp' => null,
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Rohidin -1993-01-13.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Sama',
                ],
                [
                    'id' => 1962,
                    'nama' => 'Marco Angelsen',
                    'tempat_lahir' => 'Jakarta',
                    'tgl_lahir' => '2007-08-30',
                    'agama' => 'katholik',
                    'no_telp' => '+62 811-1667-833',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Marco Angelsen -2007-08-30.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1963,
                    'nama' => 'Juan Prince Adeliant',
                    'tempat_lahir' => 'Banjarnegara',
                    'tgl_lahir' => '2003-04-20',
                    'agama' => 'Kristen',
                    'no_telp' => '+62 852-3848-0852',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Juan Prince Adeliant -2003-04-20.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1964,
                    'nama' => 'Sonia Shisuka Shantiro',
                    'tempat_lahir' => 'Denpasar',
                    'tgl_lahir' => '2000-03-13',
                    'agama' => 'katholik',
                    'no_telp' => '+62 823-3993-5162',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Sonia Shisuka Shantiro -2000-03-13.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
                [
                    'id' => 1965,
                    'kode'=> null,
                    'nama' => 'Kartika Endah Fitriani',
                    'tempat_lahir' => 'Majalengka',
                    'tgl_lahir' => '1999-02-03',
                    'agama' => 'Islam',
                    'no_telp' => '+62 858-9424-8784',
                    'email' => null,
                    'emergency_ctc' => null,
                    'hub_ec' => null,
                    'kendaraan' => null,
                    'foto_ktp' => 'KTPPenghuni/Kartika Endah Fitriani -1999-02-03.jpeg',
                    'referensi' => null,
                    'status' => 'In',
                    'status_nama' => 'Nama Berbeda',
                    'status_telp' => 'Telp Berbeda',
                ],
        ]);

        foreach ($penghuniLama as $data) {
            $penghuni = Penghuni::where('id', $data['id'])->first();

            // Jika penghuni sudah ada
            if ($penghuni) {
                // Jika nama berbeda dan telp berbeda → buat record baru
                if (
                    $data['status_nama'] === 'Nama Berbeda' &&
                    $data['status_telp'] === 'Telp Berbeda'
                ) {
                    Penghuni::create($this->mapData($data));
                    continue;
                }

                // Jika hanya nama berbeda → update nama
                if ($data['status_nama'] === 'Nama Berbeda') {
                    $penghuni->update(['nama' => $data['nama']]);
                }

                // Jika hanya telp berbeda → update no_telp
                if ($data['status_telp'] === 'Telp Berbeda') {
                    $penghuni->update(['no_telp' => $data['no_telp']]);
                }
            } else {
                // Jika tidak ditemukan, insert saja
                Penghuni::create($this->mapData($data));
            }
        }

        echo "Migrasi selesai!\n";
    }

    private function mapData(array $data): array
    {
        return [
            'id' => Str::uuid()->toString(),
            'kode' => !empty($data['kode']) ? $data['kode'] : 'PH-' . Str::upper(Str::random(7)),
            'nama' => $data['nama'],
            'tempat_lahir' => $data['tempat_lahir'],
            'tanggal_lahir' => $data['tgl_lahir'],
            'agama' => $data['agama'],
            'no_telp' => $data['no_telp'],
            'email' => $data['email'],
            'kontak_darurat' => $data['emergency_ctc'],
            'hubungan_kontak_darurat' => $data['hub_ec'],
            'kendaraan' => $data['kendaraan'],
            'foto_ktp' => $data['foto_ktp'],
            'referensi' => $data['referensi'],
            'status' => $data['status'],
        ];
    }
}
