---
deployment:
  tasks:
    - /bin/sh -c "export COMPOSER_HOME=$HOME/.composer"
    - /usr/local/bin/php /usr/local/bin/composer install --no-interaction --no-dev
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link
    - /bin/chmod 755 storage
    - /bin/chmod 755 bootstrap/cache